const PDFDocument = require('pdfkit');
const path = require('path');
const fs = require('fs');
const { getAllTransactions } = require('../models/transactionModel');
const { getAllBanks } = require('../models/bankModel');

const fraudSummaryReport = async (req, res) => {
  const transactions = await getAllTransactions();
  const banks = await getAllBanks();

  const totalTransactions = transactions.length;
  const fraudTransactions = transactions.filter((tx) => tx.risk_level === 'HIGH').length;
  const lowRisk = transactions.filter((tx) => tx.risk_level === 'LOW').length;
  const mediumRisk = transactions.filter((tx) => tx.risk_level === 'MEDIUM').length;
  const highRisk = fraudTransactions;

  const reportDir = path.join(__dirname, '../reports');
  if (!fs.existsSync(reportDir)) {
    fs.mkdirSync(reportDir, { recursive: true });
  }

  const filename = `fraud-summary-${Date.now()}.pdf`;
  const filePath = path.join(reportDir, filename);

  const doc = new PDFDocument({ size: 'A4', margin: 40 });
  doc.pipe(fs.createWriteStream(filePath));

  doc.fontSize(20).fillColor('#0b3d91').text('Fraud Summary Report', { underline: true });
  doc.moveDown();
  doc.fontSize(12).fillColor('#333333').text(`Generated by: ${req.user.name}`, { continued: true }).text(`  Role: ${req.user.role}`);
  doc.text(`Date: ${new Date().toLocaleString()}`);
  doc.moveDown();

  doc.fontSize(14).fillColor('#111111').text('Overview', { underline: true });
  doc.fontSize(12).text(`Total Transactions: ${totalTransactions}`);
  doc.text(`Fraud Transactions: ${fraudTransactions}`);
  doc.text(`Low Risk: ${lowRisk}`);
  doc.text(`Medium Risk: ${mediumRisk}`);
  doc.text(`High Risk: ${highRisk}`);
  doc.moveDown();

  doc.fontSize(14).text('Bank Analysis', { underline: true });
  banks.forEach((bank) => {
    const bankCount = transactions.filter((tx) => tx.bank_id === bank.id).length;
    doc.fontSize(12).text(`${bank.bank_name} (${bank.branch}, ${bank.address || 'Unknown address'}) - ${bankCount} transaction(s)`);
  });
  doc.moveDown();

  doc.fontSize(14).text('High Risk Transactions', { underline: true });
  const highRiskTransactions = transactions.filter((tx) => tx.risk_level === 'HIGH').slice(0, 10);
  highRiskTransactions.forEach((tx, index) => {
    doc.fontSize(12).text(`${index + 1}. ${tx.merchant} - ${tx.amount} - ${tx.location} - Score ${tx.fraud_score}`);
  });

  doc.end();

  doc.on('finish', () => {
    res.json({ message: 'Fraud summary PDF generated', path: `/reports/${filename}`, file: filename });
  });
};

module.exports = { fraudSummaryReport };
